borrower::operator bool() const
Had to take away test to compare against 0.
Use nullptr instead.

/home/dev/test/pointers_test/borrower_tests.cpp:322:27: error: use of overloaded operator '==' is ambiguous (with operand types 'mp::borrower<int *>' and 'int') [clang-diagnostic-error]
    REQUIRE(null_borrower == 0);
                          ^